version: "3"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-2022-database
    command: /bin/bash /scripts/entrypoint.sh
    volumes:
      - dbdata:/var/opt/mssql
      - ./database/scripts:/scripts
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=ApitelBank#@%#$
    ports:
      - 1433:1433
  flyway:
    image: redgate/flyway
    container_name: flyway
    command: migrate -environment=local -connectRetries=60
    volumes:
      - ./database/flyway/conf/:/flyway/conf
      - ./database/flyway/data/:/flyway/data
      - ./database/flyway/migrations/:/flyway/migrations
    depends_on:
      - db
  localstack:
    image: localstack/localstack
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  localstack_init:
    image: amazonlinux:2
    container_name: localstack-init
    command: /bin/bash /localstack-init.sh
    volumes:
      - ./localstack-init.sh:/localstack-init.sh
    depends_on:
      - localstack
  main_banking_service:
    image: eclipse-temurin:21
    container_name: main-banking-service
    working_dir: /app
    command: ./mvnw spring-boot:run
    ports:
      - 3001:3001
    volumes:
      - ./main-banking-service:/app
    depends_on:
      - db
      - localstack_init
  reporting_service:
    image: eclipse-temurin:21
    container_name: reporting-service
    working_dir: /app
    command: ./mvnw spring-boot:run
    ports:
      - 3002:3002
    volumes:
      - ./reporting-service:/app
    depends_on:
      - db
      - localstack_init
  bank_partner_service:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: bank-partner-service
    working_dir: /app
    command: dotnet watch
    ports:
      - 3003:3003
    environment:
      - ASPNETCORE_HTTP_PORTS=3003
    volumes:
      - ./bank-partner-service:/app
    depends_on:
      - db
      - localstack_init
      - reporting_service
  bank_manager_portal:
    image: node:20
    container_name: bank-manager-portal
    working_dir: /app
    command: /bin/sh -c "npm install && npm start"
    ports:
      - 3000:3000
    volumes:
      - ./bank-manager-portal:/app
    environment:
      # For react scripts, native file watching does not work/ is unreliable when in docker.
      # Instruct the dev server to use polling instead. 
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true       
    depends_on:
      - reporting_service
volumes:
  dbdata:
