name: Migrate Database
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Deploy Terraform"]
    types:
      - completed
  push:
    paths:
      - "database/flyway/migrations/**"
jobs:
  migrate:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    env:
      FLYWAY_URL: jdbc:sqlserver://${{secrets.AWS_RDS_ENDPOINT}}:1433;authentication=sqlPassword;databaseName=ApitelDB
      FLYWAY_USER: ${{ secrets.DB_USERNAME }}
      FLYWAY_PASSWORD: ${{ secrets.DB_PASSWORD }}
      FLYWAY_LOCATION: filesystem:database/flyway
    defaults:
      run:
        shell: bash
        working-directory: database/flyway/migrations
    steps:
      - name: repo setup
        uses: actions/checkout@v3

      - name: flyway setup
        run: |
          wget -qO- https://download.red-gate.com/maven/release/com/redgate/flyway/flyway-commandline/10.9.1/flyway-commandline-10.9.1-linux-x64.tar.gz | tar -xvz && sudo ln -s `pwd`/flyway-10.9.1/flyway /usr/local/bin

      - name: flyway migrations
        run: |
          flyway -configFiles="migrations/flyway.conf" migrate
